import React, { useContext, useState } from 'react';
import { useNavigate } from 'react-router';
import RouteContainer from '../components/RouteContainer';
import { AppContext } from '../context/AppContext';
import createClient from 'openapi-fetch';
import type { paths } from '../api/schema'; // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: import.meta.env.VITE_API_URL });

const RegisterView = () => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const { dispatch } = useContext(AppContext)!;
  const navigate = useNavigate();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    console.log('yes');

    try {
      const {
        data, // only present if 2XX response
        // error, // only present if 4XX or 5XX response
        response,
      } = await client.POST('/users/register/', {
        credentials: 'include',
        headers: {
          'Content-Type': 'application/json',
        },
        body: {
          username,
          password,
          email: 'wp@agh.edu.pl',
        },
      });

      if (!response.ok) throw new Error('Register failed');

      dispatch({ type: 'SET_USER', payload: data });
      navigate('/profile');
    } catch (error) {
      console.error(error);
      alert('Niepoprawne dane rejejstracji');
    }
  };

  return (
    <RouteContainer>
      <div className='hero bg-base-200 min-h-screen'>
        <div className='hero-content flex-col'>
          <div className='text-center'>
            <h1 className='text-5xl font-bold'>
              <s>Logowanie</s>Rejestracja
            </h1>
            <p className='py-6'>Podaj swoje dane aby się rejestrować</p>
          </div>
          <div className='card shrink-0 w-full max-w-sm shadow-2xl bg-base-100'>
            <form className='card-body'>
              <div className='form-control'>
                <label className='label'>
                  <span className='label-text'>Email</span>
                </label>
                <input
                  type='email'
                  placeholder='email'
                  className='input input-bordered'
                  required
                  value={username}
                  onChange={e => setUsername(e.target.value)}
                />
              </div>
              <div className='form-control'>
                <label className='label'>
                  <span className='label-text'>Hasło</span>
                </label>
                <input
                  type='password'
                  placeholder='hasło'
                  className='input input-bordered'
                  required
                  value={password}
                  onChange={e => setPassword(e.target.value)}
                />
              </div>
              <div className='form-control mt-6'>
                <button onClick={handleSubmit} className='btn btn-primary'>
                  Zaloguj się
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </RouteContainer>
  );
};

export default RegisterView;
